name: Test rerun failed jobs

on:
    pull_request:
      types: [opened, reopened, synchronize]
    push:
        branches:
            - "main"

  
jobs:
    a-passed-job: 
        runs-on: ubuntu-latest
        steps:
          - name: This job always passes
            run: echo "This step always passes..." && sleep 10

    some-other-step:
        runs-on: ubuntu-latest
        steps:
            - name: This step always fails
              run: sleep 10 && exit 1
            - name: Retry if failed
              if: failure() && fromJSON(github.run_attempt) < 3
              env:
                GH_REPO: ${{ github.repository }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: | 
                echo "Retrying..."
                gh workflow run rerun-workflow.yml -F run_id=${{ github.run_id }}
