name: Test rerun failed jobs

on:
    pull_request:
    push:
        branches:
            - "main"
        
permissions:
  actions: write
  contents: write

jobs:
    some-other-step:
        runs-on: ubuntu-latest
        steps:
            - name: This step always fails
              run: sleep 10 && exit 1
            - name: Retry if failed
              if: failure() && fromJSON(github.run_attempt) < 3
              env:
                GH_REPO: ${{ github.repository }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: | 
                echo "Retrying..."
                gh workflow run rerun-workflow.yml -F run_id=${{ github.run_id }}
