name: Test upload logs

on:
    pull_request:
      types: [opened, reopened, synchronize]
    push:
        branches:
            - "main"

jobs:
    test-job: 
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Set up JDK 8
            uses: actions/setup-java@v2
            with:
              java-version: "8"
              distribution: "adopt"
              cache: "maven"
          - name: Build and run integration tests with Maven
            run: mvn clean package 
          - name: Print path
            run: pwd