name: Test-rerun-failed-jobs

on:
    pull_request:
      types: [opened, reopened, synchronize]
    push:
        branches:
            - "main"
permissions:
    actions: write
          
  
jobs:
    a-passed-job: 
        runs-on: ubuntu-latest
        steps:
          - name: This job always passes
            run: echo "This step always passes..." && sleep 10

    some-other-step:
        runs-on: ubuntu-latest
        steps:
            - name: This step always fails
              run: sleep 10 && exit 1
